apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nitrate-tcms-demo-bfkt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nitrate-tcms-demo-bfkt
    app.kubernetes.io/part-of: nitrate-tcms-demo
  name: nitrate-tcms-demo-bfkt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: nitrate-tcms-demo-bfkt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: nitrate-tcms-demo-bfkt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cqi-tenant/nitrate-tcms-demo/nitrate-tcms-demo-bfkt@sha256:c49e0960fe47b22e7f583b5e6f0f7e706b8f45567e325786ff64292bfa1994e8
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
