apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nitrate-tcms-demo-bfkt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nitrate-tcms-demo-bfkt
    app.kubernetes.io/part-of: nitrate-tcms-demo
  name: nitrate-tcms-demo-bfkt
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: nitrate-tcms-demo-bfkt
status:
  loadBalancer: {}
