apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nitrate-tcms-demo-bfkt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/cqi-tenant/nitrate-tcms-demo/nitrate-tcms-demo-bfkt@sha256:87b3b9997801513fe1fbcd834c3fcacb9ec0d5a65972ed98cca8fe5f8c1a5e9c
        name: my-python
        resources: {}
status: {}
